# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1337a200317df430be387ed1ae8be272d5ddca7f98d5f03898198678cedda8b49bef8b5abdf4e7090b21962a66f2fb272eaa99db627eecd997df2b7ae0996e4a

test:
  secret_key_base: ab30114b472d23893ce04a104b7b7ff780a094c3c689118502851de36dbbb131aee9924336a4bab76ba4ffc0e151aa344ea7aa97f55ffa4b620e0c39f8abdcd6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
