Quote.create(text:"And I will strike down upon thee with great vengeance and furious anger those who attempt to poison and destroy my brothers. And you will know my name is the Lord when I lay my vengeance upon you!", author:"Pulp Fiction")
Quote.create(text:"And maybe one day, years from now, long after I'm dead and gone, reunited with your dear mother, you gather your whole family together and tell them the truth, who you are, where you come from. You tell them the whole story. And then you ask them if they know how lucky they are to be there. That this all came so close to never happening...", author:"25th Hour")
Quote.create(text:"Before he was the Mad Ducats guy, he was just Pickle Fucker. You see, freshman year, the seniors would hunt us down and put us through what they called 'initiations.' They'd stuff us into lockers or throw us in the girl's shower room nekkid, but Lance here got the worst of it. The seniors yanked down his pants and shoved a pickle up his a** and made him walk ten feet. If the pickle fell out before he hit the ten-foot mark, he had to take a bite of it, re-insert it, and walk again.", author:"Clerks II")
Quote.create(text:"Cinderella story. Outta nowhere. A former greenskeeper, now, about to become the Masters champion. It looks like a mirac... It's in the hole! It's in the hole! It's in the hole!", author:"Caddyshack")
Quote.create(text:"Don't talk like one of them; 'You're Not! Even if you'll like to be. To them, you're just a freak; Like me. They need you right now, but when they don't... They'll cast you out, like a Leper. See their morals.. Their Code.. It's a bad joke, dropped at the first sign of trouble... They're only as good as the world allows them to be. I'll show you, when the chips are down, these uhhh, these Civilized people... They'll eat each other... See I'm not a monster, I am just ahead of the curve...", author:"The Dark Knight")
Quote.create(text:"For what it's worth: it's never too late or, in my case, too early to be whoever you want to be. There's no time limit, stop whenever you want. You can change or stay the same, there are no rules to this thing. We can make the best or the worst of it. I hope you make the best of it. And I hope you see things that startle you. I hope you feel things you never felt before. I hope you meet people with a different point of view. I hope you live a life you're proud of. If you find that you're not, I hope you have the strength to start all over again.", author:"The Curious Case of Benjamin Button")
Quote.create(text:"How about this for a number, six. That's how old my other daughter is. eight is the age of my son. Two is how many times I've been married and divorced. Sixteen is the number of dollars I have in my bank account. 850-3943. That's my phone number, and with all the numbers I gave you, I'm guessing zero is the number of times you're gonna call it.", author:"Erin Brockovich")
Quote.create(text:"I don't know who you are. I don't know what you want. If you are looking for ransom, I can tell you I don't have money. But what I do have are a very particular set of skills; skills I have acquired over a very long career. Skills that make me a nightmare for people like you. If you let my daughter go now, that'll be the end of it. I will not look for you, I will not pursue you. But if you don't, I will look for you, I will find you, and I will kill you.", author:"Taken")
Quote.create(text:"I'm angry. I'm very angry, Ralph. You know, you can ball my wife if she wants you to. You can lounge around here on her sofa, in her ex-husband's dead-tech, post-modernistic bullshit house if you want to. But you do not get to watch my f**king television set!", author:"Heat")
Quote.create(text:"Listen to me, mister. You're my knight in shining armor. Don't you forget it. You're going to get back on that horse, and I'm going to be right behind you, holding on tight, and away we're gonna go, go, go!", author:"On Golden Pond")
Quote.create(text:"Oh, I see, what I should do is, er, come home and say 'Hi honey! Guess what? I walked into this house today, where this junkie ashole just fried his baby in a microwave, because it was crying to loud. So let me share that with you. Come on, let's share that, and in sharing it, we'll somehow, er, cathartically dispel all that heinous shit'. Right?", author:"Heat")
Quote.create(text:"Someday? Someday my dream will come? One night you will wake up and discover it never happened. It's all turned around on you. It never will. Suddenly you are old. Didn't happen, and it never will, because you were never going to do it anyway. You'll push it into memory and then zone out in your barco lounger, being hypnotized by daytime TV for the rest of your life. Don't you talk to me about murder. All it ever took was a down payment on a Lincoln town car. That girl, you can't even call that girl. What the fuck are you still doing driving a cab?", author:"Collateral")
Quote.create(text:"The unlucky are nothing more than a frame of reference for the lucky. You are unlucky, so I may know that I am not. Unfortunately the lucky never realize they are lucky until it's too late. Take yourself for instance; yesterday you were better off than you are off today but it took today for you to realize it. But today has arrived and it's too late. You see? People are never happy with what they have. They want what they had, or what others have. The grass is always greener on the other side.", author:"Lucky Number Slevin")
Quote.create(text:"You don't live with me, you live among the remains of dead people. You sift through the detritus, you read the terrain, you search for signs of passing, for the scent of your prey, and then you hunt them down. That's the only thing you're committed to. The rest is the mess you leave as you pass through.", author:"Heat")
Quote.create(text:"You know what I've noticed?! Nobody panics when everything goes according to 'plan'. I could say, tomorrow I'm gonna blow up a truckload of gangbangers... or soldiers... Nobody panics, because it's all apart of the plan... but, if I say I'm gonna kill one itty bitty mayor... then everyone loses their minds!! Introduce a little anarchy, upset the established order, and it becomes chaos... I'm an agent of chaos... and, you know the thing about chaos... it's fair", author:"The Dark Knight")

count = 0 
15.times do
  count += 1
  User.create(name: Faker::Name.name, image: "http://vignette3.wikia.nocookie.net/smurfs/images/b/bd/Papa_Smurf123.png/revision/latest?cb=20130805130238")
  25.times do
  	Score.create(score: rand(25..90), user_id: count)
  end
end